#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://bright-softwares.com              # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Put your telegram channel on autopilot

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Full Bright                                
your_link                                 : https://bright-softwares.com                     
your_city                                 : Paris                                
email_address                             : full3right@gmail.com
facebook_username                         :                                           
instagram_username                        : #
twitter_username                          : t0o1
github_username                           : fullbright
youtube_username                          : UCd6CVmyAAvetQX3R8zglKgg



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Engage your members with timed messages
    description                           : Tell your members the remaining time before your event occur to keep them engaged.
    fontawesome_icon_name                 : magic
    
  - title                                 : Plan ahead many events and their announcement
    description                           : Register your events in the app and let it do all the heavy lifting for you.
    fontawesome_icon_name                 : mobile

  - title                                 : Emojis supprt
    description                           : Add emojis to your message to engage your members.
    fontawesome_icon_name                 : play-circle

  - title                                 : Easy to Tweak
    description                           : Tweak messages, emojis and countdown time for your messages.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Events List
    description                           : Easily review upcoming events and manage from right from Telegram.
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
